### ISSUE TITLE
Week 01 - Day 2 - Expanding your world

### ISSUE THREAD

**Issue by mdewey** [PerseusRipple/assignments#2]
# Expanding Your World

In this assignment, you will end up with a simple styled web page, published on the web.

Create a new website that shows some basic styling and formatting using HTML and CSS. This website should help share some information for one of your favorite hobbies.

## Objectives

- Practice using your tools text editor
- Explore new CSS properties
- Publish a web page

## Requirements

- Have `git`, `hub`, and `node` installed. We should have done this together in class.

### Explorer Mode

- [ ] Follow all of the setup instructions (See "Assignment Setup").
- [ ] Create a new `app-app` project.
- [ ] Using CSS, style your page to imitate some of the classic designs of the web. Feel free to make this look as "bad" as you want. Here are some sites to gain inspiration:
  - [10 90s websites designs you won’t believe existed](https://www.justinmind.com/blog/10-90s-websites-designs-you-wont-believe-existed/)
- [ ] Add a second page about your hobby with (at least) 2 pictures and with other facts about your hobby.
- [ ] Add a menu to your site so a user can go back and forth between the new pages.
- [ ] Between the 2 pages, use at least 5 tag selectors, 5 id selectors, and 5 class selectors to style content on your page.
- [ ] Deploy your site.

### Adventure Mode

- [ ] use pseudo-classes to style elements when you hover the mouse over them
- [ ] Add a third page, that has a table. Create this table to have alternating colored rows and a hover over color.
- [ ] Make a nav bar that sticks to the top of the page (see the nav bar here for example - https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes)
- [ ] Make a footer that always sticks to the bottom of the page

### Epic Mode

- [ ] Explore CSS animations and add some life to your static page. Feel free to really dig into these and try to animate all elements on your page to some extent

### CSS

- [Cool game to learn CSS selectors](https://flukeout.github.io/)
- [Introduction to CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS)
- [Getting Started with CSS Rules](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#Anatomy_of_a_CSS_ruleset)
- [All the CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#Keyword_index)
- [pseudo-classes and pseudo-elements](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Pseudo-classes_and_pseudo-elements)
- [http://www.csszengarden.com/](http://www.csszengarden.com/)

### HTML

- [HTML Tags](https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags)
- [Evolution of the Web](http://www.evolutionoftheweb.com)

## Reading Material

To prep for tomorrow's lesson, you can [read about flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

**Comment by PerseusRipple** [comment]
https://my-hobbies-PerseusRipple.netlify.com

I don't know why it deployed to netlify and not github like before. also, it's incomplete. thank you.

**Comment by gstark** [comment]
Hi Shantell, please copy the *https://github.com* link to your assignment and place it here. We usually don't need the *netlify.com* link but rather the github one.

From what I can see from your deployed netlify, the homework seems acceptable. Once I see the github.com link I can mark the assignment complete.

Thank you!
Gavin

**Comment by PerseusRipple** [comment]
https://github.com/PerseusRipple/my-hobbies

Please let me know if this is not the link you need or the assignment is unacceptable. Thank you.

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBVZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--978506c32fc72f81eabd7234e584cda7e38900af/giphy-6.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/71)**__
